// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SisAluguel.Context;

namespace SisAluguel.Migrations
{
    [DbContext(typeof(SisAluguelContexto))]
    partial class SisAluguelContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SisAluguel.Models.Aluguel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cd_aluguel");

                    b.Property<Guid>("ClienteId")
                        .HasColumnName("cd_cliente");

                    b.Property<DateTime>("DataDeDevolucao")
                        .HasColumnName("dd_aluguel");

                    b.Property<DateTime>("DataDeEmprestimo")
                        .HasColumnName("de_aluguel");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("db_aluguel","dbo");
                });

            modelBuilder.Entity("SisAluguel.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cd_cliente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nm_cliente");

                    b.Property<string>("Telefone")
                        .HasColumnName("tf_cliente");

                    b.HasKey("Id");

                    b.ToTable("db_cliente","dbo");
                });

            modelBuilder.Entity("SisAluguel.Models.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cd_livro");

                    b.Property<Guid?>("AluguelId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nm_livro")
                        .HasMaxLength(100);

                    b.Property<int>("SituacaoAluguel")
                        .HasColumnName("st_livro");

                    b.HasKey("Id");

                    b.HasIndex("AluguelId");

                    b.ToTable("db_livro","dbo");
                });

            modelBuilder.Entity("SisAluguel.Models.Aluguel", b =>
                {
                    b.HasOne("SisAluguel.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SisAluguel.Models.Livro", b =>
                {
                    b.HasOne("SisAluguel.Models.Aluguel", "Aluguel")
                        .WithMany("Livros")
                        .HasForeignKey("AluguelId");
                });
#pragma warning restore 612, 618
        }
    }
}
